# Utiliser une image Node.js officielle comme image de base
FROM node:22

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code de l'application
COPY . .

# Exposer le port 3010
EXPOSE 3010

# Démarrer l'application
CMD ["npm", "start"]